### ISSUE TITLE
代码规范建议.

### ISSUE THREAD

**Issue by joesonw** [ui-model/ui-model#1]
趁着刚开源, 最好把架子搭好, 不然东西不规范, 大家贡献起来也不方便. 例如, tslint之类的, doc/命名规范等等.

**Comment by asnowwolf** [comment]
好的，现在在探索API风格，接下来就开始做这些。

**Comment by asnowwolf** [comment]
提交了第一版，加了gulp任务，支持自动tslint和test。请review。

**Comment by joesonw** [comment]
@asnowwolf 只是提一些建议啦, travis呀, commit-hook也这些也方便大家贡献代码, 以免浪费一些不必要的时间在review和rework上. 另外建议你们注册一个 ui-model的npm账号, 这样方便归类包, 例如`@ui-model/kernel` 这样发布包.

**Comment by asnowwolf** [comment]
恩，稍后就开始搭建基础设施。

**Comment by asnowwolf** [comment]
Done. thank you!
